name: Contribute

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Run every 1 hours

jobs:
  contributor:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Git with Personal Info
      env:
        GITHUB_EMAIL: ${{ secrets.GH_EMAIL }}
        GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
      run: |
        git config --local user.email "$GITHUB_EMAIL"
        git config --local user.name "$GITHUB_USERNAME"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run Python script
      run: python main.py  # Runs the main.py script

    - name: Commit files
      run: |
        git add contrib.txt

    - name: Push changes
      run: |
        git push origin main  # Push the changes to the main branch
