name: Contribute

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Run every hour

jobs:
  contributor:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Git with Personal Info
      env:
        GITHUB_EMAIL: ${{ secrets.GH_EMAIL }}
        GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
      run: |
        git config --local user.email "$GITHUB_EMAIL"
        git config --local user.name "$GITHUB_USERNAME"

    - name: Append text to file
      run: |
        echo "1" >> contrib.txt
        echo "Text appended to contrib.txt"

    - name: Commit changes
      run: |
        git add contrib.txt
        git commit -m "✨NEW CONTRIBUTION✨"

    - name: Push changes
      run: |
        git push origin main  # Push the changes to the main branch
