name: Contribute

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Run every hour

jobs:
  contributor:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Git with Personal Info
      env:
        GITHUB_EMAIL: ${{ secrets.GH_EMAIL }}
        GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
      run: |
        git config --local user.email "$GITHUB_EMAIL"
        git config --local user.name "$GITHUB_USERNAME"

    - name: Update contrib.txt
      run: |
        # Check if contrib.txt exists; if not, initialize it with 0
        if [ ! -f contrib.txt ]; then
          echo "0" > contrib.txt
        fi
        
        # Read the current value, increment it, and overwrite the file
        current=$(cat contrib.txt)
        next=$((current + 1))
        echo $next > contrib.txt

        echo "Updated contrib.txt with value: $next"

    - name: Determine commit message
      id: commit_msg
      run: |
        # Determine the suffix (st, nd, rd, th) for the contribution number
        case $((next % 10)) in
          1) suffix="st" ;;
          2) suffix="nd" ;;
          3) suffix="rd" ;;
          *) suffix="th" ;;
        esac
        
        # Special cases for 11th, 12th, and 13th
        if [ $((next % 100)) -ge 11 ] && [ $((next % 100)) -le 13 ]; then
          suffix="th"
        fi
        
        # Form the commit message
        echo "message=${next}${suffix} contribution" >> $GITHUB_ENV

    - name: Commit changes
      run: |
        git add contrib.txt
        git commit -m "${{ env.message }}"

    - name: Push changes
      run: |
        git push origin main  # Push the changes to the main branch
